### ISSUE TITLE
Error caused by alerts_to_add is nil

### ISSUE THREAD

**Issue by DRESAAN** [raiguard/Factorio-LtnManager#114] opened 2020-09-25 10:57 UTC
#### Describe the Bug

While loading a save game I get the following error message:
Die Mod LTN - Logistisches Bahnnetzwerk (1.14.5) hat einen Fehler verursacht, der nicht behoben werden kann.
Bitte informiere den Autor der Mod über diesen Fehler.

Error while running event LogisticTrainNetwork::on_configuration_changed
Die Mod LTN Manager [ALPHA] (0.3.5) hat einen Fehler verursacht, der nicht behoben werden kann.
Bitte informiere den Autor der Mod über diesen Fehler.

Error while running event LtnManager::Custom event (ID 234)
__LtnManager__/scripts/ltn-data.lua:39: attempt to get length of field 'alerts_to_add' (a nil value)
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:39: in function <__LtnManager__/scripts/ltn-data.lua:12>
stack traceback:
	__LogisticTrainNetwork__/script/train-events.lua:115: in function 'TrainArrives'
	__LogisticTrainNetwork__/script/init.lua:243: in function 'updateAllTrains'
	__LogisticTrainNetwork__/script/init.lua:336: in function <__LogisticTrainNetwork__/script/init.lua:312>
stack traceback:
	[C]: in function 'raise_event'
	__LogisticTrainNetwork__/script/train-events.lua:115: in function 'TrainArrives'
	__LogisticTrainNetwork__/script/init.lua:243: in function 'updateAllTrains'
	__LogisticTrainNetwork__/script/init.lua:336: in function <__LogisticTrainNetwork__/script/init.lua:312>

#### To Reproduce

1. Load Savegame

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

Upload the save file where the bug occured. If the file is too large for GitHub, use an alternative file service.

Please also provide your in-game username so I can reproduce the conditions exactly.

_IF YOU DO NOT UPLOAD A SAVE FILE AND PROVIDE YOUR USERNAME, THE BUG REPORT WILL BE IGNORED UNTIL YOU DO._

#### Log file

Attach `factorio-current.log`, found in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

**Comment by raiguard** [comment] 2020-09-26 00:31
Thanks for following the template, but you forgot to actually attach your save file. :)

**Comment by raiguard** [comment] 2020-09-26 00:48
Duplicate of #113

**Comment by raiguard** [comment] 2020-09-26 00:49
^ Just pretend none of that happened...

**Comment by DRESAAN** [comment] 2020-09-26 13:27
The error disapeared in v3.6

**Comment by raiguard** [comment] 2020-09-26 15:42
Oh, OK.

**Closed by raiguard** 2020-09-26 15:42 UTC
Labels: bug, needs more info
