### ISSUE TITLE
LTN Manager crashes after Update to 0.18.29

### ISSUE THREAD

**Issue by Domanaik** [raiguard/Factorio-LtnManager#76] opened 2020-06-01 17:48 UTC
On 0.18.28 everything was working fine.

![image](https://user-images.githubusercontent.com/63446985/83437824-b46b1400-a440-11ea-9c3d-cd3732288607.png)

**Comment by Domanaik** [comment] 2020-06-01 17:52
[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/4712724/factorio-current.log)
[Uploading LTN_ExtendedPlus.zip…]()

**Comment by Domanaik** [comment] 2020-06-01 18:08
If I load an older autosave (10 min earlier) it is working. Maybe it's not related to 0.18.29 and something else went wrong..

**Comment by wvanlammeren** [comment] 2020-06-01 19:39
I get the same error here upon starting factorio after the updateM

`The mod LTN Manager [ALPHA] (0.2.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/gui/main-tabs/depots.lua:173: bad argument #1 of 2 to 'ipairs' (table expected, got nil)
stack traceback:
	[C]: in function 'ipairs'
	__LtnManager__/scripts/gui/main-tabs/depots.lua:173: in function 'update'
	__LtnManager__/scripts/gui/main.lua:328: in function 'update'
	__LtnManager__/scripts/gui/main.lua:355: in function 'update_active_tab'
	__LtnManager__/scripts/gui/main.lua:282: in function 'create'
	__LtnManager__/control.lua:171: in function <__LtnManager__/control.lua:157>`

And the same behaviour; loading a autosave of one minute before gives no problem.
also after a restart it works just fine

**Comment by raiguard** [comment] 2020-06-18 00:39
Duplicate of #74

**Closed by raiguard** 2020-06-18 00:39 UTC
Labels: bug
