### ISSUE TITLE
Cannot open LTN Manager

### ISSUE THREAD

**Issue by cbassett1000** [raiguard/Factorio-LtnManager#25] opened 2020-04-11 03:51 UTC
Error while running event LtnManager::ltnm-toggle-gui (ID 179)
Unknown sprite "ltnm_indicator_signal-Y"
stack traceback:
	__RaiLuaLib__/lualib/gui.lua:110: in function 'recursive_build'
	__RaiLuaLib__/lualib/gui.lua:168: in function 'recursive_build'
	__RaiLuaLib__/lualib/gui.lua:208: in function 'build'
	__LtnManager__/gui/depots.lua:93: in function 'update'
	__LtnManager__/gui/main.lua:267: in function 'update'
	__LtnManager__/gui/main.lua:286: in function 'update_active_tab'
	__LtnManager__/gui/main.lua:291: in function 'open'
	__LtnManager__/gui/main.lua:317: in function 'toggle'
	__LtnManager__/control.lua:192: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>
stack traceback:
	[C]: in function 'add'
	__RaiLuaLib__/lualib/gui.lua:110: in function 'recursive_build'
	__RaiLuaLib__/lualib/gui.lua:168: in function 'recursive_build'
	__RaiLuaLib__/lualib/gui.lua:208: in function 'build'
	__LtnManager__/gui/depots.lua:93: in function 'update'
	__LtnManager__/gui/main.lua:267: in function 'update'
	__LtnManager__/gui/main.lua:286: in function 'update_active_tab'
	__LtnManager__/gui/main.lua:291: in function 'open'
	__LtnManager__/gui/main.lua:317: in function 'toggle'
	__LtnManager__/control.lua:192: in function 'handler'
	__RaiLuaLib__/lualib/event.lua:127: in function <__RaiLuaLib__/lualib/event.lua:28>

I attempted to open the manager with Ctrl T and received this error.  Single Player LTN Manager 0.1.4   Existing save, just installed LTN Manager.

**Comment by raiguard** [comment] 2020-04-11 04:21
Duplicate of #21

**Closed by raiguard** 2020-04-11 04:21 UTC
Labels: bug
