### ISSUE TITLE
Multiplayer Error

### ISSUE THREAD

**Issue by cbassett1000** [raiguard/Factorio-LtnManager#26] opened 2020-04-11 03:55 UTC
I get two technical errors when joining a MP server. In the client log is the following:
 416.554 Error ClientMultiplayerManager.cpp:1106: mod-LtnManager was not registered for the following events when the map was saved but has registered them as a result of loading: Custom event (ID 205)
 416.554 Error ClientMultiplayerManager.cpp:1108: mod-LtnManager was registered for the following events when the map was saved but has not re-registered them as a result of loading: Custom event (ID 203)
 416.554 Error ClientMultiplayerManager.cpp:98: MultiplayerManager failed: "" + multiplayer.script-event-mismatch + "
" + "
mod-LtnManager"

On screen I get the following:

Cannot join. The following mod event handlers are not identical between you and the server. This indicates that the following mods are not multiplayer (save/load) safe. (see the log file for more detail):

mod-LtnManager

LTN Manager 0.1.4  Save file did not previously have LTN Manager enabled. Now does. Save file has never seen 0.17.  Only .18.17 and .18.18

**Comment by raiguard** [comment] 2020-04-11 04:19
If you happen to have Death Markers, Recipe Book, or Quick Item Search enabled, please disable them. There is some black magic going on with the interactions between those mods to cause this issue, and I am completely in the dark as to why. It's an ongoing process, but it might take me a long time to fix this problem.

**Comment by raiguard** [comment] 2020-04-11 04:22
This is also a duplicate of #19

**Closed by raiguard** 2020-04-11 04:22 UTC
Labels: bug
