### ISSUE TITLE
Mod LTN Manager [Alpha] (0.3.2) crashed after redesign Trainstations

### ISSUE THREAD

**Issue by H4nSolo** [raiguard/Factorio-LtnManager#109] opened 2020-09-20 15:13 UTC
#### Describe the Bug

In my Seablock Modpack i use LTN Alpha 0.3.2 & LTN Combinater.
I have 2 Traindepot a 22 Stations [1x for Short Trains, 1x for Long Trains]
After disconnect the outgoing Tracks from the Stations and cut the Signal Lines between LTN Combinator and LTN Stations, i get the Full Crash Report from Factorio and returns to the Main Menu.

![Factorio Error Image](https://puush.mgc4you.de/9K5UbS)

#### To Reproduce

I think, this error / crash too difficulty to reproduce, because there are probably too many factors connected.

But the fact is that Factorio produces the error after disconnecting the green signal line in one of the train depots.

Assumption: The mod trains may not be able to internally mark / recognize the still open orders as "order not executable"

#### Save file & Username

SaveFile: https://www.file-upload.net/download-14296346/_autosave3.zip.html

If the complete modpack is needed, please let me know, I will upload it later.

#### Log file

Log File: https://www.file-upload.net/download-14296353/factorio-current.log.html

**Comment by raiguard** [comment] 2020-09-21 22:56
Unfortunately, Chrome won't let me download your save file because it doesn't trust the website that you used. However, I am fairly confident that I know what the issue is and have hopefully fixed it for the next release.

Once that version releases, please try it out again and let me know if the issue has been fixed.

**Comment by raiguard** [comment] 2020-09-22 01:30
Closing this for now, will re-open if it turns out the bug hasn't been fixed.

**Closed by raiguard** 2020-09-22 01:30 UTC
Labels: bug
