### ISSUE TITLE
Crash when modifying stuck train.

### ISSUE THREAD

**Issue by Malidictus** [raiguard/Factorio-LtnManager#172] opened 2022-01-03 02:21 UTC
#### Describe the Bug

I have a specific instance where stopping an LTN Train, changing its composition and sending it back on its automated way causes an unrecoverable error.

The mod LTN Manager (0.4.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:760: attempt to index field 'main_locomotive' (a nil value)
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:760: in function '?'
	__LtnManager__/scripts/ltn-data.lua:1074: in function 'iterate'
	__LtnManager__/control.lua:175: in function <__LtnManager__/control.lua:160>

#### To Reproduce

1. A train is stuck at station "Red Engines Lube" with too much Lubricant.
2. Set train to Manual so it doesn't drive away.
3. Remove the middle train car to clear the Lubricant from the train.
4. Replace the middle cart to complete the train
5. Set train to Auto.
6. Game crashes at first LTN update after this.

#### Save file & Username

Save file at: https://www.dropbox.com/s/mn5zpsmw7lnc6jo/_autosave2.zip?dl=0
In-game player name Malidictus.

#### Log file

Log file:
https://www.dropbox.com/s/7witqm0waiy2js2/factorio-current.log?dl=0

**Comment by Malidictus** [comment] 2022-01-03 02:48
Addendum: I tried multiple approaches to solve the crash, and most of them failed. Deconstructing the train entirely still crashed me on the next LTN update after the deconstruction. Destroying the train (deconstruct, stick in a chest, shoot chest) didn't help - still crashed. JUST setting the train to Manual and back to Auto crashed me.

What ended up working was to clear out the train's schedule entirely and send it to a random station. Wait for LTN update to register that the train is no longer in the LTN network. After that, send it back to the depot. Wait for an LTN update to register the train as part of the LTN network again. This avoided the crash.

After this, I got an LTN Manager error reporting a failed deliver to Red Engines Lube, because I'd taken the train off its schedule. I suspect "something" about the train's erroneous status caused LTN Manager to fail to get a reference to it through LTN.

**Comment by raiguard** [comment] 2022-01-23 19:26
Duplicate of #168.

**Closed by raiguard** 2022-01-23 19:26 UTC
Labels: bug

**Comment by raiguard** [comment] 2022-01-23 19:37
I tried reproducing this on your map, but there is no train at the Red Engines Lube station. One does get there eventually, but it doesn't get stuck. I have band-aided a fix but haven't yet found the underlying issue.

**Comment by Malidictus** [comment] 2022-01-23 19:41
Hm... That's quite odd, my apologies. I'll retry the save I uploaded. It should have gotten stuck due to uneven load distribution. If that save doesn't work, then I don't think I can provide a new one, as I can't recreate the issue and I don't have the original save file any more, beyond what's uploaded.

**Comment by raiguard** [comment] 2022-01-23 19:46
Well, I did apply a band-aid fix, so it won't crash any more. Let me know if you experience any strange behavior!

**Comment by Malidictus** [comment] 2022-01-23 19:48
Will do. I got the fix already, will post if I run into any further issues. So far, though, this is quite literally the only issue I've had with the LTN Manager at all. Thank you for your work.

**Comment by raiguard** [comment] 2022-01-23 20:56
No problem!
