### ISSUE TITLE
0.2.3 Mod ERROR

### ISSUE THREAD

**Issue by eisstoss** [raiguard/Factorio-LtnManager#90] opened 2020-06-19 12:34 UTC
#### Describe the Bug

Mod crashes and cannot enter the game afterwards

#### To Reproduce

When I enter the game and use the shortcut key to open LtnManager, the game reports an error and crashes

#### Save file & Username

The game save is relatively large, I saved the error code, please check
#### Log file

```
Error while running event LtnManager::on_configuration_changed
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	__LtnManager__/scripts/gui/main.lua:375: in function 'close'
	__LtnManager__/control.lua:88: in function <__LtnManager__/control.lua:77>
stack traceback:
	[C]: in function '__newindex'
	__LtnManager__/scripts/gui/main.lua:375: in function 'close'
	__LtnManager__/control.lua:88: in function <__LtnManager__/control.lua:77>
```

**Comment by raiguard** [comment] 2020-06-19 15:03
The bug report template specifically states that _I still need a save file_, even if it is large! I cannot fix an error if I cannot reproduce it, and often times the erroring save file is the only way for me to do that!

If it is too large for GitHub, please upload it to Google Drive or Dropbox and post a link.

**Comment by eisstoss** [comment] 2020-06-19 15:49
After closing the MOD, I can enter the saved game normally.
After entering, I created a new save file and started MOD again to read it normally.
The saved file of the attachment is the content automatically saved by the game, which cannot be read after trying before sending
google drive link:
https://drive.google.com/file/d/1_TIj9GyY8jqOPSeckB9Zjye_pPs0j_bb/view?usp=sharing

**Comment by raiguard** [comment] 2020-06-23 21:03
This should be fixed with the most recent version. Clicking the LTNM button will cause the GUI to be re-built if the mod detects that it was invalidated. Please give it a try!

**Comment by raiguard** [comment] 2020-06-23 21:37
Please try the latest version, I believe that it should fix this issue.

**Comment by eisstoss** [comment] 2020-06-24 02:24
tks you😀

**Closed** 2020-06-24 03:21 UTC
Labels: bug
