### ISSUE TITLE
Error while running event LtnManager::on_tick (ID 0)

### ISSUE THREAD

**Issue by achman741** [raiguard/Factorio-LtnManager#80] opened 2020-06-09 03:31 UTC
I was messing around with LTN learning how it works and went to add the LTN cominator mod, latest version from a month ago is not compatable with latest version of either factorio or LTN, and there is a 'fixed' version in the comments that wanted to try, and after added that mod this error occurred, i uninstalled that mod and got the same error, so it may not be that mod. I am using a large mod list for may space exploration version 3.0 play through.  I am  not sure what caused this, may be a issue with another mod.  I'm not sure what I exactly did to cause this as this is a test world I was using to mess with varying things such as LTN.  If you try syncing the mod list skip the shortcuts mod as its a manually fixed mod.
```
The mod LTN Manager [ALPHA] (0.2.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/gui/main.lua:340: attempt to index field 'main' (a nil value)
stack traceback:
	__LtnManager__/scripts/gui/main.lua:340: in function 'update_active_tab'
	__LtnManager__/control.lua:176: in function <__LtnManager__/control.lua:157>
```

[AmatorSpace testing 2.zip](https://github.com/raiguard/Factorio-LtnManager/files/4749776/AmatorSpace.testing.2.zip)

[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/4749780/factorio-current.log)

![bug](https://user-images.githubusercontent.com/4545011/84103292-a0935500-a9e0-11ea-9b4b-66a87b7a3666.PNG)

**Comment by gleedy** [comment] 2020-06-12 13:43
I also get this error.
[New Again Once More.zip](https://github.com/raiguard/Factorio-LtnManager/files/4771099/New.Again.Once.More.zip)

**Comment by raiguard** [comment] 2020-06-18 02:13
@achman741 When I try to load up your save, the mods don't even load properly. Did you make local changes to any of them?

![image](https://user-images.githubusercontent.com/3515394/84969927-ed5ce700-b0d6-11ea-973c-c7f2fb22b7ee.png)

**Comment by raiguard** [comment] 2020-06-18 02:13
@gleedy I can't reproduce it on that save either. If you manage to get the error again, please let me know!

**Comment by raiguard** [comment] 2020-06-18 02:36
So, by some miracle, while I was working on one of the other bugs on a different save file, this happened! So it is now fixed for the next release. :D

**Closed** 2020-06-18 05:11 UTC
Labels: bug
