### ISSUE TITLE
Crash when deconstructing trains.

### ISSUE THREAD

**Issue by mig5323** [raiguard/Factorio-LtnManager#175] opened 2022-01-06 01:04 UTC
I'm using Train Scaling to switch out my trains to a higher tier train.
When sending a train to the special station that will automatically deconstruct it, it sometimes crashes. Sorry for non-reproducibility. :(

3356.890 Error MainLoop.cpp:1284: Exception at tick 79649328: The mod LTN Manager (0.4.8) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__LtnManager__/scripts/ltn-data.lua:760: in function '?'
	__LtnManager__/scripts/ltn-data.lua:1074: in function 'iterate'
	__LtnManager__/control.lua:175: in function <__LtnManager__/control.lua:160>

**Comment by Kinetic27** [comment] 2022-01-23 07:20
![image](https://user-images.githubusercontent.com/39849944/150668626-6868bdb5-38c6-4f93-9c12-c8d7f7b3494c.png)
me too
If I manually change the train and erase it, it does get erased.

**Comment by raiguard** [comment] 2022-01-23 19:47
Duplicate of #168

**Closed by raiguard** 2022-01-23 19:47 UTC
