### ISSUE TITLE
"Could not find Train ID" crash

### ISSUE THREAD

**Issue by PSquared1234** [raiguard/Factorio-LtnManager#97] opened 2020-07-24 23:07 UTC
#### Describe the Bug

Hello. I've been having an occasional issue with LTN Manager that causes a crash. I finally managed to get a repeatable save file to provide you.

Here's a screen shot of the crash: https://steamcommunity.com/sharedfiles/filedetails/?id=2176688394. (I now realize this is redundant with the log file).

#### To Reproduce

The attached save file ("_autosave-quick3.zip") will reliably cause this crash within 30s or less (game time 7 days, 6:29:24). No user input is required.

I've also included the log file, as you request.

[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/4974523/factorio-current.log)
[_autosave-quick3.zip](https://github.com/raiguard/Factorio-LtnManager/files/4974524/_autosave-quick3.zip)

I don't understand the relevance of my (presumably Factorio) user name, but it's "P_Squared". Perhaps this is relevant for multiplayer games? At any rate, there it is.

I hope this helps you nail down this issue. Currently it causes my game to crash every 30 minutes or so (perhaps more so as my train activity goes up). I was a big fan of the original mod, and I'm glad you've been able to revive it for today's Factorio. I find it indispensable when using LTN. I hope this information is helpful.

Regards,

P^2

**Comment by raiguard** [comment] 2020-07-25 02:04
Thanks for the report. This is a duplicate of #91, but I ended up using your save file to find and fix the bug, so I won't mark this as invalid. :)

**Closed** 2020-07-25 02:58 UTC
Labels: bug
