### ISSUE TITLE
error in 3.2

### ISSUE THREAD

**Issue by ztnko** [raiguard/Factorio-LtnManager#110] opened 2020-09-21 12:09 UTC
#### Describe the Bug
![factorio_LpHA11IL7W](https://user-images.githubusercontent.com/70898037/93764769-627f1180-fc1c-11ea-9d3a-92c8192678c3.png)

#### To Reproduce
every time i enter game

#### Save file & Username
[k2_meiten1.zip](https://github.com/raiguard/Factorio-LtnManager/files/5255220/k2_meiten1.zip)
ztn
#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-LtnManager/files/5255219/factorio-current.log)

**Comment by SGZ-TW-TY-20** [comment] 2020-09-21 22:32
https://cdn.discordapp.com/attachments/697564089907675217/757725073779064832/unknown.png

Have the same issue. just mine are not in Russian

**Comment by raiguard** [comment] 2020-09-21 23:19
Duplicate of #105

**Closed by raiguard** 2020-09-21 23:19 UTC
Labels: bug

**Comment by ztnko** [comment] 2020-09-22 08:48
yes i see that it duplicates but i also see from discussion there that you can't constantly reproduce bug with that saves. in my save bug 100% time i load game.

**Comment by raiguard** [comment] 2020-09-22 16:03
Yeah, in that case you could have replied to that other issue instead of making a new one. Regardless, the issue has been solved now, and your save was the one that I ended up using to solve it. So, thank you!
