### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by luaotix** [raiguard/Factorio-LtnManager#150] opened 2021-11-16 17:35 UTC
I updated the new version 0.4.0 of LTN Manager, and the game failed to open twice, as shown below:

Error while running event LtnManager::on_configuration_changed
__LtnManager__/scripts/player-data.lua:24: attempt to call method 'destroy' (a nil value)
stack traceback:
	__LtnManager__/scripts/player-data.lua:24: in function 'refresh'
__LtnManager__/control.lua:61: in function <__LtnManager__/control.lua:53>

Just now, in the game, I found that LTN indicated that the fluid of the truck was not cleaned up, and then I clicked the map to check the station, and the error occurred again, which is shown as follows:

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:541: attempt to compare nil with string
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:541: in function <__LtnManager__/scripts/ltn-data.lua:540>
	[C]: in function 'sort'
	__LtnManager__/scripts/ltn-data.lua:540: in function 'callback'
	__flib__/table.lua:233: in function <__flib__/table.lua:205>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:1073: in function 'iterate'
__LtnManager__/control.lua:166: in function <__LtnManager__/control.lua:151>

I like your mod very much, and hope to fix this problem, thanks.

**Comment by JPLeo** [comment] 2021-11-17 02:58
This just happened in my Krastorio game and a friend's Space Exploration one, Recipe Book also has a similar problem, had to disable both of them.

The mod LTN Manager (0.4.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_tick (ID 0)
__LtnManager__/scripts/ltn-data.lua:541: attempt to compare string with nil
stack traceback:
	__LtnManager__/scripts/ltn-data.lua:541: in function <__LtnManager__/scripts/ltn-data.lua:540>
	[C]: in function 'sort'
	__LtnManager__/scripts/ltn-data.lua:540: in function 'callback'
	__flib__/table.lua:233: in function <__flib__/table.lua:205>
	(...tail calls...)
	__LtnManager__/scripts/ltn-data.lua:1073: in function 'iterate'
	__LtnManager__/control.lua:166: in function <__LtnManager__/control.lua:151>

**Comment by raiguard** [comment] 2021-11-17 03:34
@luaotix Thanks for the report, fixed for the next release.

@JPLeo Duplicate of #149

**Closed** 2021-11-17 03:39 UTC
Labels: bug
